### ISSUE TITLE
#7 - Red Flowers

### ISSUE THREAD

**Issue by ttamura0** [cornerstonecollege/beezy-bee#7]
Even though, a bee  touch a red flower, sometimes, you can't get points.

**Comment by luizperes** [comment]
This bug seems to have been fixed. https://github.com/cornerstonecollege/beezy-bee/commit/748749368da708d2b2e35bff1824a3c2fcc81cd6

There were extra pixels of another image inside this one. This might have been a problem, since we are using [SKPhysicsBody bodyWithTexture:self.texture size:self.size]; on BEEBaseTouchable
