### ISSUE TITLE
Gravity/weight seems inconsistent

### ISSUE THREAD

**Issue by damathews** [cornerstonecollege/beezy-bee#8]
Hi,

I noticed that the different bees seem to fall differently or do not accelerate upwards the same across all the characters. Is there somewhere that changes the height of each tap for different characters?

Thank you!

**Comment by luizperes** [comment]
Hi @damathews ,
Thanks for your considerations!

I think that, as we did not set the `mass` of the player's `physicsBody`, it seems that SpriteKit is setting this value proportionally by the size of one's physicsBody.

We are concerned of that and we decided to leave it like that, as it seems to be "**harder**" or "**easier**" depending on the character selected, making the game a bit more challenging.

I imagine that it can be easily `fixed` by updating the BEEPlayer.m on line 53:

```
- (void) initilizePlayerWithParent:(SKScene *)parent
{
    if ([parent isKindOfClass:[GameScene class]])
    {
        GameScene *gameScene = ((GameScene *)parent);
        gameScene.eventsDelegate = self;
        __weak BEEPlayer *weakSelf = self;
        [gameScene.timerDelegateArr addObject:weakSelf];

        self.physicsBody.categoryBitMask = BEE_PLAYER_MASK;
        self.physicsBody.dynamic = YES;
        self.physicsBody.allowsRotation = NO;

        // I think we should include a code similar to this one below:
        self.physicsBody.mass = 0.02; // In fact we would need to test a good mass for all of them
    }
}
```

Again,
Thank you,
Luiz.

**Comment by damathews** [comment]
Thank you very much for the reply Luiz. I added in the code but now the bee disappears on the first tap.

**Comment by luizperes** [comment]
No problem @damathews ,
It happens because of the details below:

File `GameScene.m` line 47:

```
- (void) addPhysicsWorld
{
    self.physicsWorld.gravity = CGVectorMake( 0.0, -5.0);
    self.physicsWorld.contactDelegate = self;
}
```

In the file above, we are setting the gravity of our "World" to `-5.0`, in oppose to `-9.8`, which is Earth's gravity and thus, it is also SpriteKit's default value.

Now, let us check what is happening on our `BEEPlayer` file, line 85:

```
- (void)didTap
{
    // Too much
    //SKAction *sound = [SKAction playSoundFileNamed:@"bee_fly.mp3" waitForCompletion:NO];
    //[self runAction:sound];

    if (self.position.y < self.parent.frame.size.height)
    {
        self.physicsBody.velocity = CGVectorMake(0, 0);
        [self.physicsBody applyImpulse:CGVectorMake(0, 200)];
    }
}
```

 As you can see in this method, we are applying a force of `200` in the `Y Axis`, but as we modified our player's `physicsBody.mass` to `0.02`, I think that we should also change the impulse we are making on **line 94**... I would guess that `[self.physicsBody applyImpulse:CGVectorMake(0, 10)];` is a good value to start with.

Moreover, the player is disappearing from the screen only by the fact that **200** is a huge number compared with its `mass` versus the world's `gravity`.

In my opinion, as the world's gravity is `(0, -5)`, we can apply a force of `(0, 10)`, as a double value against the `gravity`. The `player's mass` is very small, so I think it can be disconsidered.

If the `player` is `too heavy` or `too light`, please try to adjust the value of its `physicsBody.mass` or the force applied on the `didTap` method.

```
// We adjusted our [self.physicsBody applyImpulse...] to (0, 200) after some test.
// Now, as you are setting the player's mass, you should probably adjust the impulse too. :)
```

Another thing is, [here](https://developer.apple.com/library/ios/documentation/SpriteKit/Reference/SKPhysicsBody_Ref/#//apple_ref/occ/instp/SKPhysicsBody/mass) shows that in fact, the `player's physicsBody.mass` is calculated by the size of its physicsBody (if we do not set) versus its `density`. **That is why our players have different mass by default**.

I hope it helps.

**Comment by damathews** [comment]
That's perfect. I think that took care of my problem. Thank you so much for your detailed response!
