### ISSUE TITLE
Advice/Help for making it work on iPads

### ISSUE THREAD

**Issue by damathews** [cornerstonecollege/beezy-bee#9]
I am having trouble making the game compatible with iPads. I changed it to Universal from iPhone but I think I need to change the storyboard in order for it to scale to various size screens. Is this what you would recommend? 
Thank you!

**Comment by luizperes** [comment]
Hi @damathews, 
Beezy Bee does not use its storyboard in order to become lighter, can you please send me the screenshots of the problems?

Thanks,
Luiz.

**Comment by damathews** [comment]
Thanks Luiz. I seemed to work okay on smaller iPads but a few have the top get cutoff. It is set to universal so I would guess the sizing of objects may increase with the larger resolution?
![screen shot 2016-04-21 at 6 17 20 pm 2](https://cloud.githubusercontent.com/assets/17294944/14726062/924b915e-07ed-11e6-8d39-744789b33332.png)

**Comment by luizperes** [comment]
Hi @damathews, this problem seems to be related to the background asset files in [here](https://github.com/cornerstonecollege/beezy-bee/tree/master/beezy-bee/beezy-bee/Assets.xcassets). We were not considering the support to tablets, although, if you need to change the size of the background image, you can find all their respective `*.ai`files [here](https://github.com/cornerstonecollege/beezy-bee/tree/master/art-design)..

You would need to update all 3 backgrounds one by one... there is nowhere to run.
I'm sorry we did not think about that when we were developing it....

If you have any other problem, please do not hesitate to message me! :D

Thanks,
Luiz.
